/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.api;


import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class PersonServiceTest {
    @Test public void testGetAll() {
    }
}
